spring.application.name=inventory-api
# inventory feign client
logging.level.com.example.inventory.client=DEBUG
# OpenAPI configuration
springdoc.show-actuator=true
springdoc.use-management-port=true
# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
management.endpoints.web.exposure.include=openapi, swagger-ui
